spring:
  banner.location: classpath:mapper.banner
  main:
    show-banner: true
server:
  port: 8080   # здесь слушает http-server
  session-timeout: 5
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
management:
  endpoint:
    health:
      show-details: always
my:
   par1: value_of_paraameter1
